#!/usr/bin/env python3
"""
Chain of Command Test Script:
1. Generates an inspiring ~100-word essay on the topic "Everything is possible"
   using the offline local GGUF model (pulsar-final-q4_k_m).
2. Executes a structured Chain of Command:
   - Step 1: LLM Content Generation (Local Model)
   - Step 2: File Creation & Persistence on Desktop (Essay.txt)
   - Step 3: Application Launch & Window Focus (Notepad.exe)
   - Step 4: Verification of File Content and Active Process
"""

import os
import sys
import time
import subprocess
from datetime import datetime
from pathlib import Path

# Ensure stdout handles UTF-8 on Windows terminal
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')

# Setup paths
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))
sys.path.insert(0, str(PROJECT_ROOT / "backend"))
sys.path.insert(0, str(PROJECT_ROOT / "core_ai" / "src"))

def get_desktop_path() -> Path:
    """Find the user's Desktop directory on Windows."""
    user_profile = os.environ.get("USERPROFILE")
    if user_profile:
        desktop = Path(user_profile) / "Desktop"
        if desktop.exists():
            return desktop
    desktop = Path.home() / "Desktop"
    desktop.mkdir(parents=True, exist_ok=True)
    return desktop

def main():
    print("=" * 65)
    print("  CHAIN OF COMMAND TEST: LOCAL AI ESSAY -> NOTEPAD -> DESKTOP")
    print("=" * 65)
    
    chain_start_time = time.time()
    steps_total = 4
    
    # -------------------------------------------------------------
    # STEP 1: AI Content Generation (Local GGUF Model)
    # -------------------------------------------------------------
    print(f"\n[STEP 1/{steps_total}] Querying Local GGUF Model for Essay...")
    topic = "artificial intelligence"
    prompt = (
        f"Write an inspiring essay of about 100 words on the topic: '{topic}'. "
        "Do not include introductory greetings or concluding conversational filler. "
        "Provide only the essay text."
    )
    
    try:
        from ai_assistant.ai.llm_provider import UnifiedChatInterface
        
        chat = UnifiedChatInterface(provider="gguf", use_fallback=False)
        print(f"   Using Provider: {chat.provider_name} | Model: {chat.model}")
        
        t0 = time.time()
        essay_text = chat.chat(prompt, stream=False)
        gen_duration = time.time() - t0
        
        # Clean up any potential markdown headers or extra quotes
        essay_text = essay_text.strip().strip('"')
        word_count = len(essay_text.split())
        
        print(f"   Generated in {gen_duration:.2f}s | Word count: {word_count} words")
        print("\n--- [ESSAY PREVIEW] ---")
        print(essay_text)
        print("-----------------------\n")
        
    except Exception as e:
        print(f"❌ [STEP 1 FAILED] Could not generate essay with local model: {e}")
        import traceback
        traceback.print_exc()
        return False

    # -------------------------------------------------------------
    # STEP 2: File Creation & Persistence on Desktop
    # -------------------------------------------------------------
    print(f"[STEP 2/{steps_total}] 💾 Saving Essay to Desktop as Easy.txt...")
    desktop_dir = get_desktop_path()
    file_path = desktop_dir / "easy.txt"
    
    try:
        header = f"Topic: {topic}\nDate: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\nGenerated by: Local Pulsar AI (Offline GGUF)\n\n"
        full_content = header + essay_text + "\n"
        
        file_path.write_text(full_content, encoding="utf-8")
        print(f"   Saved successfully to: {file_path}")
        print(f"   File size: {file_path.stat().st_size} bytes")
    except Exception as e:
        print(f"❌ [STEP 2 FAILED] Failed to write file to desktop: {e}")
        return False

    # -------------------------------------------------------------
    # STEP 3: Launch Notepad with Essay
    # -------------------------------------------------------------
    print(f"[STEP 3/{steps_total}] 📱 Launching Notepad with the Essay...")
    try:
        # Launch Notepad directly opening the saved file
        process = subprocess.Popen(["notepad.exe", str(file_path)])
        print(f"   Notepad launched with PID: {process.pid}")
        time.sleep(1.5)  # Allow window to initialize and display
        
    except Exception as e:
        print(f"❌ [STEP 3 FAILED] Failed to launch Notepad: {e}")
        return False

    # -------------------------------------------------------------
    # STEP 4: Verification
    # -------------------------------------------------------------
    print(f"[STEP 4/{steps_total}] 🔍 Verifying Execution Results...")
    if not file_path.exists():
        print(f"❌ Verification failed: {file_path} does not exist!")
        return False
        
    read_back = file_path.read_text(encoding="utf-8")
    if topic not in read_back or len(read_back.split()) < 30:
        print("❌ Verification failed: Content mismatch or empty file!")
        return False
        
    total_duration = time.time() - chain_start_time
    print("   File on Desktop: Verified ✅")
    print("   Notepad Window: Running ✅")
    print("   AI Content Integrity: Verified ✅")
    
    print("\n" + "=" * 65)
    print(f"🎉 CHAIN OF COMMAND COMPLETED SUCCESSFULLY IN {total_duration:.2f}s!")
    print("=" * 65)
    return True

if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)
